apiVersion: 1

deleteDatasources:
  - name: PostgreSQL-Direct
    orgId: 1
  - name: Prometheus
    orgId: 1
  - name: Tempo
    orgId: 1

datasources:

  - name: Prometheus
    type: prometheus
    uid: prometheus-lab
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Tempo
    type: tempo
    uid: tempo-lab
    access: proxy
    url: http://tempo:3200
    editable: true
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus-lab

  - name: PostgreSQL-Direct
    type: postgres
    uid: postgres-direct
    access: proxy
    url: postgres:5432
    user: grafana_ro
    secureJsonData:
      password: grafana_ro_pass
    jsonData:
      database: labdb
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    editable: true